### ISSUE TITLE
solar_system/solar_main.py

### ISSUE THREAD

**Issue by kolganovn** [python-practice-b02-006/gribova_akulov#2]
Сделайте выход не по эскейпу, а по кнопочке крестик, а то не очев, что нужно жать эскейп.

**Comment by gribovanika** [comment]
а это яисправила

**Comment by kolganovn** [comment]
У меня теперь ни крестик ни эскейп не работают

**Comment by gribovanika** [comment]
всё закрывается, если несколько раз на крестик нажать
