### ISSUE TITLE
усложнение карты для проекта

### ISSUE THREAD

**Issue by gribovanika** [python-practice-b02-006/gribova_akulov#3]
Предлагаю лабиринт усложнить для того, чтобы было интереснее искать точки для телепортации.

**Comment by abacaba01** [comment]
done

**Comment by abacaba01** [comment]
надо сделать возможность заходить в игру 2 раза

**Comment by gribovanika** [comment]
это я добавила. вход можно осуществить через рандомный промежуток времени от 20-40 секунд
